#!/usr/bin/env bash
#This script displays numbers 1 to 100 with fizzbuzz rules
i=1; while [ "i" -le 100 ]; do if [ $((i%15)) -eq 0 ]; then echo "fizzbuzz"; elif [ $((i%3)) -eq 0 ]; then echo "fizz"; elif [ $((i%5)) -eq 0 ]; then echo "buzz"; else echo "
i"; fi; i=$((i+1)); done
