#!/usr/bin/env bash
#This script displays username user id and home directory from /etc/passwd
while IFS=: read -r username password uid gid info home shell; do echo "username:username:
username:uid:$home"; done < /etc/passwd
