#!/usr/bin/env bash
#This script displays Best School 10 times using while loop
i=1; while [ "i"−le10];doecho"BestSchool";i=i" -le 10 ]; do echo "Best School"; i=
i"−le10];doecho"BestSchool";i=((i+1)); done
