#!/usr/bin/env bash
#This script displays numbers 1 to 20 with superstitious messages
i=1; while [ "i"−le20];doecho"i" -le 20 ]; do echo "
i"−le20];doecho"i"; case "i"in4)echo"badluckfromChina";;9)echo"badluckfromJapan";;17)echo"badluckfromItaly";;esac;i=i" in 4) echo "bad luck from China";; 9) echo "bad luck from Japan";; 17) echo "bad luck from Italy";; esac; i=
i"in4)echo"badluckfromChina";;9)echo"badluckfromJapan";;17)echo"badluckfromItaly";;esac;i=((i+1)); done
